### ISSUE TITLE
Put a z index in the css

### ISSUE THREAD

**Issue by ForgeableSum** [englercj/phaser-debug#11]
.pdebug {
z-index: 9999; 
}

Otherwise games that go full window or full screen won't be able to see the UI and will think it simply doesn't work (like I did until I figured it out).

**Comment by ForgeableSum** [comment]
There are some other problems I found with the css... it automatically hides all input checkboxes. Is this such a good idea?

**Comment by englercj** [comment]
All the css should be namespaced to the debug window. It shouldn't effect your page.

---

Edit: I see the error in the less, I'll commit a fix right now to fix the namespacing.
