### ISSUE TITLE
Wrap all css rules in .pdebug

### ISSUE THREAD

**Issue by francisberesford** [englercj/phaser-debug#7]
Nice plugin btw!

Just a small improvement.. I'm using this plugin in a project that has bootstrap (css framework) and all my checkboxes are being changed to toggle images (which incidentally I cant see where they're used in the debug interface anyway)

I think it would be better if all css rules began with .pdebug
e.g.

```.pdebug .checkbox { ... } ```

**Comment by englercj** [comment]
They do in `main.less`, looks like I forgot it in `forms.less`.

**Comment by englercj** [comment]
5694a7eba76d5470aac6dbda94ef668398e49491
