### ISSUE TITLE
Cant use the plugin help wanted

### ISSUE THREAD

**Issue by birozz** [englercj/phaser-debug#8]
I tried to add the line this.game.add.plugin(Phaser.Plugin.Debug); on every place possible resulting similar error messages like below.
I think I am doing something wrong but cant figure out how to use it properly.
My index file : http://pasted.co/b3274898
My game file :http://pasted.co/d68e4594
Error msg : http://i.xomf.com/dlvrd.png

Browser Chromium Version 42.0.2311.90 (64-bit)

**Comment by englercj** [comment]
A couple things I notice:

1. You are including phaser twice, both the minified and unminified versions. Only include one of them.
2. The error about a syntax error in phaser-debug probably means you are not actually loading the library, but something else instead.

Please post a *running* example of it being broken for me to debug. Thanks!

**Comment by birozz** [comment]
Here is my game project : http://3life.co.nf/Samur/ 
It that enoug ?
Thanx !

**Comment by englercj** [comment]
Just like I thought:

http://3life.co.nf/Samur/js/lib/phaser-debug.js

That isn't the debug script.

**Comment by birozz** [comment]
Stupid mistake ... Thanx for your help :)
