### ISSUE TITLE
Click on 'Scene Tree' == Uncaught TypeError

### ISSUE THREAD

**Issue by doggan** [englercj/phaser-debug#9]
Repro:
- Click on Scene Tree button
- Uncaught TypeError is logged:
```
Uncaught TypeError: Expecting a function in instanceof check, but got undefinedtypeToString @ phaser-debug.js:1292
module.exports.HandlebarsCompiler.template.main @ phaser-debug.js:1021
ret @ phaser-debug.js:732
Scene.rebuildTree @ phaser-debug.js:1222
Scene.show @ phaser-debug.js:1249Panel.toggle @ phaser-debug.js:1073
(anonymous function) @ phaser-debug.js:231
(anonymous function) @ phaser-debug.js:1603
```

Environment:
- Phaser v2.4.4
- Chrome Version 46.0.2490.80 (64-bit) (Mac OS X)

This seems to fix it (in `typeToString`):
```
-        if (node instanceof PIXI.Stage) {
+        if (typeof PIXI.Stage !== 'undefined' &&
+            node instanceof PIXI.Stage) {
```

**Comment by doggan** [comment]
Here's a simple repro case:
```
git clone -b phaser_debug_repro --single-branch https://github.com/doggan/diablogl.git
```

Open up `./client/index.html` and click on the 'Scene Tree' button. You'll see the error in the console at this line:
<img width="269" alt="screen shot 2015-11-02 at 8 30 12 am" src="https://cloud.githubusercontent.com/assets/517857/10887649/1a4be622-813d-11e5-938d-8454a666dca5.png">

Notes:
- Code: https://github.com/doggan/diablogl/tree/phaser_debug_repro/client
- Note that I'm including Phaser before the Phaser-Debug plugin.
- Adding in the change in my PR, and the root object will display as: `PIXI DisplayObjectContainer`.

**Comment by englercj** [comment]
The phaser build you have down't look like it includes pixi at all...

**Comment by doggan** [comment]
I just confirmed using Phaser from CDN: `PIXI.Stage` is defined in Phaser 2.4.3 but not in Phaser 2.4.4.

Phaser 2.4.3:
https://jsfiddle.net/hn3f22Lm/
```
2.4.3
(index):29 function
```

Phaser 2.4.4:
https://jsfiddle.net/rasmz9no/
```
2.4.4
(index):29 undefined
```

Perhaps @photonstorm could shed some light?

**Comment by JamesSkemp** [comment]
For what it's worth, I'll second that 2.4.4 throws the above error when clicking on the Scene Tree button. Downgrading to Phaser 2.4.3 works as expected.

Happens on both Chrome 46 and Microsoft Edge 20.10240.16384.0. Using version 1.1.6 of the plugin.

Very nifty plugin, by the way.

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/commit/b99c9e22ecc471e40432d544f41e333f2397548b

In your game code just do `PIXI.Stage = Phaser.Stage` and it should map fine then. Not sure if this plugin does anything special with the stage or not, but I suspect not, probably just iterates it?

**Comment by englercj** [comment]
@photonstorm It does `instanceof` on it, it is the "auto determine type" logic.

**Comment by doggan** [comment]
@englercj Should I close my PR (https://github.com/englercj/phaser-debug/pull/10) if you think this is not the correct fix?

It doesn't affect me one way or the other, as I've been using your plugin with the above workarounds. It would probably be nice to get a fix into master, though, for anyone else who happens to upgrade to Phaser 2.4.4+, as they will run into the same issue.

Thanks again for the great plugin. :sparkles:

**Comment by englercj** [comment]
I would merge #10 now that I understand the issue, if you also added support for Phaser.Stage in there as well.

**Comment by doggan** [comment]
Added. Please check it out.
